/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AnalyzeUsernameRouteImport } from './routes/analyze.$username'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareResultsRouteImport } from './routes/compare.results'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles.index'
import { Route as AuthenticatedRolesSlugRouteImport } from './routes/_authenticated/roles.$slug'
import { Route as OauthGithubReturnRouteImport } from './routes/oauth/github/return'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AnalyzeUsernameRoute = AnalyzeUsernameRouteImport.update({
  id: '/analyze/$username',
  path: '/analyze/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareResultsRoute = CompareResultsRouteImport.update({
  id: '/compare/results',
  path: '/compare/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesSlugRoute = AuthenticatedRolesSlugRouteImport.update({
  id: '/roles/$slug',
  path: '/roles/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OauthGithubReturnRoute = OauthGithubReturnRouteImport.update({
  id: '/oauth/github/return',
  path: '/oauth/github/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/recruiter': typeof RecruiterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/compare/results': typeof CompareResultsRoute
  '/compare/': typeof CompareIndexRoute
  '/roles/$slug': typeof AuthenticatedRolesSlugRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/recruiter': typeof RecruiterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/compare/results': typeof CompareResultsRoute
  '/compare': typeof CompareIndexRoute
  '/roles/$slug': typeof AuthenticatedRolesSlugRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/recruiter': typeof RecruiterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/compare/results': typeof CompareResultsRoute
  '/compare/': typeof CompareIndexRoute
  '/_authenticated/roles/$slug': typeof AuthenticatedRolesSlugRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/recruiter'
    | '/dashboard'
    | '/roadmap'
    | '/analyze/$username'
    | '/checkout/success'
    | '/compare/results'
    | '/compare/'
    | '/roles/$slug'
    | '/oauth/github/return'
    | '/roles/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/recruiter'
    | '/dashboard'
    | '/roadmap'
    | '/analyze/$username'
    | '/checkout/success'
    | '/compare/results'
    | '/compare'
    | '/roles/$slug'
    | '/oauth/github/return'
    | '/roles'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/recruiter'
    | '/_authenticated/dashboard'
    | '/_authenticated/roadmap'
    | '/analyze/$username'
    | '/checkout/success'
    | '/compare/results'
    | '/compare/'
    | '/_authenticated/roles/$slug'
    | '/oauth/github/return'
    | '/_authenticated/roles/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  RecruiterRoute: typeof RecruiterRoute
  AnalyzeUsernameRoute: typeof AnalyzeUsernameRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CompareResultsRoute: typeof CompareResultsRoute
  CompareIndexRoute: typeof CompareIndexRoute
  OauthGithubReturnRoute: typeof OauthGithubReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/analyze/$username': {
      id: '/analyze/$username'
      path: '/analyze/$username'
      fullPath: '/analyze/$username'
      preLoaderRoute: typeof AnalyzeUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/results': {
      id: '/compare/results'
      path: '/compare/results'
      fullPath: '/compare/results'
      preLoaderRoute: typeof CompareResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/$slug': {
      id: '/_authenticated/roles/$slug'
      path: '/roles/$slug'
      fullPath: '/roles/$slug'
      preLoaderRoute: typeof AuthenticatedRolesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/github/return': {
      id: '/oauth/github/return'
      path: '/oauth/github/return'
      fullPath: '/oauth/github/return'
      preLoaderRoute: typeof OauthGithubReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedRolesSlugRoute: typeof AuthenticatedRolesSlugRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedRolesSlugRoute: AuthenticatedRolesSlugRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  RecruiterRoute: RecruiterRoute,
  AnalyzeUsernameRoute: AnalyzeUsernameRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CompareResultsRoute: CompareResultsRoute,
  CompareIndexRoute: CompareIndexRoute,
  OauthGithubReturnRoute: OauthGithubReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
